apiVersion: batch/v1
kind: Job
metadata:
  name: jl-scanvi-test-${NAME}
spec:
  backoffLimit: 5
  completions: 1
  template:
    metadata:
      labels:
        k8s-app: jl-scanvi-test-${NAME}
    spec:
      restartPolicy: Never
      containers:
      - name: jl-scanvi-test-${NAME}
        image: jmlehrer/scvi-benchmark:latest
        command: ["stdbuf", "-i0", "-o0", "-e0", "bash", "-c"]
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        args: [
          "wandb login --relogin $(cat wandbcreds) && \
          python scanvi_${NAME}_model.py"
        ]
        resources:
          limits:
            memory: 128Gi
            cpu: "16"
            nvidia.com/gpu: "1"
          requests:
            memory: 64Gi
            cpu: "16"
            nvidia.com/gpu: "1"
        volumeMounts:
        - name: ephemeral
          mountPath: "/data"
        # SystemV shared memory
        - name: "dshm"
          mountPath: "/dev/shm"
      volumes:
      # Ephemeral storage
      - name: ephemeral
        emptyDir: {}
      - name: dshm
        emptyDir:
          medium: Memory
      tolerations:
        - key: "nautilus.io/chase-ci"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
