apiVersion: batch/v1
kind: Job
metadata: 
  name: jl-feature-weights
spec:
  backoffLimit: 5
  completions: 1
  template:
    metadata:
      labels:
        k8s-app: jl-feature-weights
    spec:
      restartPolicy: Never
      containers:
      - name: jl-feature-weights
        image: jmlehrer/sims:latest
        command: ["stdbuf", "-i0", "-o0", "-e0", "bash", "-c"]
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        args: [
          "python for_paper/feature_masks.py"
        ]
        resources:
          limits:
            memory: 256Gi
            cpu: "32"
            nvidia.com/gpu: "1"
          requests:
            memory: 64Gi
            cpu: "32"
            nvidia.com/gpu: "1"
        volumeMounts:
        - name: ephemeral
          mountPath: "/data"
        # SystemV shared memory
        - name: "dshm"
          mountPath: "/dev/shm"
      volumes:
      # Ephemeral storage
      - name: ephemeral
        emptyDir: {}
      - name: dshm
        emptyDir:
          medium: Memory
